### ISSUE TITLE
Can't create Device instance

### ISSUE THREAD

**Issue by jaraco** [jaraco/jaraco.video#6]
Originally reported by: **Curtis Maloney (Bitbucket: [funkybob](http://bitbucket.org/funkybob), GitHub: [funkybob](http://github.com/funkybob))**

---

Have tried latest pip version and BB repo from today, and get the same result:

```
#!python

>>> c = capture.Device(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\jaraco\video\capture.py", line 54, in __init__
    self.initialize()
  File "C:\Python27\lib\site-packages\jaraco\video\capture.py", line 94, in initialize
    None,
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

Python 2.7.11 (32bit)
Windows 7 Professional (64bit)

---
- Bitbucket: https://bitbucket.org/jaraco/jaraco.video/issue/6

**Comment by pi-cjm** [comment]
Seems the core of the problem is that device has no VfW drivers, only DirectShow.  After setting the flag for OpenCV to use DSHOW, it worked there...
