### ISSUE TITLE
ImportError: cannot import name 'tag_AMMediaType'

### ISSUE THREAD

**Issue by solarjoe** [jaraco/jaraco.video#9]
When trying to use the module I get

```
from comtypes.gen.DexterLib import SampleGrabber, tag_AMMediaType
ImportError: cannot import name 'tag_AMMediaType'
```
I was looking through the generated modules in `comtypes/gen` I saw that `DexterLib.py`

only provides 

```
class _AMMediaType(Structure):
    pass
```

When I changed 'tag_AMMediaType' to `_AMMediaType` it worked fine.

(Windows 7 64-bit, Python 3.4, comtypes 1.1.7) 

By the way, thanks for providing the code. It finally got me started while trying to 
control my UVC webcam using DirectShow with Python.

**Comment by jaraco** [comment]
It's been forever since I've worked with this package. Given that DexterLib is a generated package, I'd hope it could be re-generated and that would fix the issue. I'd like to avoid making patches to generated code if possible.

**Comment by jaraco** [comment]
Oh, re-reading the bug report, the issue is in some other file that's importing from DexterLib.

**Comment by jaraco** [comment]
I've noticed that with late runs, the name that appears is once again `tag_AMMediaType`, so I'm going to change it back.
